# Generated by Django 3.1.5 on 2021-03-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
